Librarie de reservation
Guidap/booking.js pull request #1
Opened 2018-10-04 08:15 UTC by BrunoGuerrero

Creation d'une librarie de reservation.

2018-10-05 14:27 UTC, SylvainMarty requested changes

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +    }
Préférer mettre ce code à la fin du fichier vu qu'il n'est utile que pour les 2 dernières lignes du fichier 😉 
On peut même le simplifier un peu : 
```js
window.GUIDAP = window.GUIDAP || {};
window.GUIDAP.booking = new Booking();
```

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +                event = window.event;
Y a un cas où l'event fournit peut être vide/undefined ? 🤔

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            this.iframeElement.setAttribute('src', 'http://' + this.domain + '/app_dev.php/export/full/' + uuid);
L'URL ici ne doit pas tout le temps contenir `/app_dev.php/` car en prod l'environnement de dev est désactivé.
Il te faut regarder la valeur de la variable globale `NODE_ENV` qui est injectée par Webpack au build du fichier.
Soit `NODE_ENV` est vide, soit elle vaut `production` 👍 

Pense aussi qu'en prod, on utilise HTTPS et c'est nécessaire pour le paiement en ligne via l'iframe 😉 Par contre c'est du HTTP en dev ^^

> Pour la petite histoire, la variable est ajoutée au fichier généré par Webpack au moment du back et est en réalité une bête constante :)

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
Faire un fichier séparé `icons.js` dans lequel tu déclares le/les svg du projet.
On est pas limité à un seul fichier pour dev donc autant en profiter :)

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +        this.iframeElement = null;
Du coup tu exposes tout, même ce dont on a pas besoin à l'extérieur ?
Rien ne t'empêche de faire des `let` pour les données qui ne doivent pas sortir de l'usage interne de la classe :)

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            // Creates a full page veil
Créer une méthode privée dédiée 👍

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            // Creates a modal on veil
Idem 👍

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            // Creates a close button
Idem 👍

2018-10-05 14:27 UTC, SylvainMarty commented on src/index.js
> +            // Creates iframe used to display activity page
Créer une méthode privée dédiée 👍

2018-10-05 14:28 UTC, SylvainMarty commented
C'est du beau taf globalement avec du JS natif, c'est cool et le poids de la lib va bien s'en ressentir 👍 
Par contre je suis revenu sur du découpage des méthodes internes car la méthode `init()` est huuuge :$

2018-10-05 14:35 UTC, BrunoGuerrero commented on src/index.js
> +                event = window.event;
Fallback en cas de navigateur foireux qui gère mal les events. C'est ce qui était recommandé :D

2018-10-05 15:30 UTC, BrunoGuerrero commented on src/index.js
> +        this.iframeElement = null;
Corrigé

2018-10-05 15:30 UTC, BrunoGuerrero commented on src/index.js
> +            // Creates a full page veil
Done

2018-10-05 15:31 UTC, BrunoGuerrero commented on src/index.js
> +            // Creates a modal on veil
Done

2018-10-05 15:31 UTC, BrunoGuerrero commented on src/index.js
> +            // Creates a close button
Done

2018-10-05 15:31 UTC, BrunoGuerrero commented on src/index.js
> +            // Creates iframe used to display activity page
Done

2018-10-05 15:42 UTC, SylvainMarty commented on src/index.js
> +                event = window.event;
Okay pour c'est legit !
@kmonmousseau Un avis là dessus ?

2018-10-05 15:53 UTC, SylvainMarty commented on src/index.js
>      GUIDAP.booking = new Booking();
Ça risque rien ça ? Ta variable est dans `window`, on est sûr que tous les navigateurs seront faire ?
J'suis d'avis de mettre le préfixe `window.` de manière explicite, histoire de dire 👀

2018-10-05 15:53 UTC, SylvainMarty commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
Est-ce que c'est toujours prévu de le mettre dans un fichier à part ? (cf [commentaire](https://github.com/Guidap/booking.js/pull/1#discussion_r223024742))

2018-10-05 15:53 UTC, SylvainMarty commented on src/index.js
> +            _iframeElement.setAttribute('src', 'http://' + _domain + '/app_dev.php/export/full/' + uuid);
Ne pas oublié de gérer le scheme (http ou https) et l'URL de dev ou on en fonction de l'environnement 👀  (cf [commentaire](https://github.com/Guidap/booking.js/pull/1#discussion_r223024263))

2018-10-05 16:02 UTC, BrunoGuerrero commented on src/index.js
> +            this.iframeElement.setAttribute('src', 'http://' + this.domain + '/app_dev.php/export/full/' + uuid);
Done :)

2018-10-05 16:06 UTC, BrunoGuerrero commented on src/index.js
>      GUIDAP.booking = new Booking();
Done

2018-10-05 16:06 UTC, BrunoGuerrero commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
Oué je ferai ça lundi. Mais ouais

2018-10-08 08:16 UTC, SylvainMarty commented on src/index.js
> +            let path = (isProduction ? "" : "/app_dev.php") + '/export/full/' + uuid;
Utiliser des single quotes 👀

2018-10-08 08:18 UTC, SylvainMarty commented on src/index.js
> +            let isProduction = (process.env.NODE_ENV === 'production');
Parenthèses inutiles :)
Tu as testé le build ? Ce check fonctionnement correctement ? :)

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +        /** Creates root element for modal to be displayed
met le commentaire sur la ligne du dessous non ?
oui chipotage, mais normalement on écrit pas sur la ligne d'ouverture du commentaire

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
vu la taille, ça me parait loin d'être déconnant de l'avoir dedans

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +                event = window.event;
si c'est nécessaire, j'y ai aucune objection 😄

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +                event.stopPropagation();
un `event.preventDefault()` serait pas nécessaire aussi ? parce que sinon on aura la comportement par défaut du lien/bouton, même si on bubble pas l'event

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +            let isProduction = (process.env.NODE_ENV === 'production');
oui inutiles :)

2018-10-08 08:31 UTC, kmonmousseau commented on src/index.js
> +            _contentElement.appendChild(_createCloseButton());
pourquoi avoir fait le append ici avec le résultat retrourné par la fonction et pour les autres se baser sur les var ?

2018-10-08 08:31 UTC, kmonmousseau commented
good job c'est clean 👍

2018-10-08 08:35 UTC, BrunoGuerrero commented on src/index.js
> +            let path = (isProduction ? "" : "/app_dev.php") + '/export/full/' + uuid;
Done

2018-10-08 08:39 UTC, BrunoGuerrero commented on src/index.js
> +            let isProduction = (process.env.NODE_ENV === 'production');
Pour un build de prod le code fonctionne correctement. Pour un build de dev je n'en ai aucune confirmation, n'ayant toujours pas pu utiliser la lib de dev.

2018-10-08 08:42 UTC, BrunoGuerrero commented on src/index.js
> +            _contentElement.appendChild(_createCloseButton());
CloseElement n'est réutilisé nulle part, là où Content, Root et Iframe element sont réexploités après leur utilisation.

2018-10-08 08:45 UTC, BrunoGuerrero commented on src/index.js
> +        /** Creates root element for modal to be displayed
Done

2018-10-08 08:46 UTC, BrunoGuerrero commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
Damn je saisis pas le commentaire, qu'entends-tu par là ?

2018-10-08 08:48 UTC, BrunoGuerrero commented on src/index.js
> +            let isProduction = (process.env.NODE_ENV === 'production');
Les parentèses ont été virées

2018-10-08 08:59 UTC, BrunoGuerrero commented on src/index.js
> +                event.stopPropagation();
Done

2018-10-08 12:29 UTC, kmonmousseau commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
je veux dire que de garder le SVG ici (ne pas en faire un fichier à part) ne me parait pas déconnant, ça évite de load une ressource supplémentaire (sachant que c'est un SVG très léger)

2018-10-08 12:31 UTC, kmonmousseau commented on src/index.js
> +            _contentElement.appendChild(_createCloseButton());
ça se tient 😄

2018-10-08 12:35 UTC, kmonmousseau commented on src/index.js
>           *
du coup ligne inutile
```js
/**
 * Creates root element for modal to be displayed
 */
```

#monsieurrelou

2018-10-08 12:35 UTC, kmonmousseau commented on src/index.js
> +         *
plein de sauts de ligne !! (je sais je suis relou avec ça, mais ça me fait le même effet que de griffer un tableau pour certains)

2018-10-08 13:05 UTC, BrunoGuerrero commented on src/index.js
> +            closeElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" style="height:100%" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path fill="4c4c4c"
A voir alors lorsque l'on aura à réutiliser celle-là, ou a utiliser une nouvelle icone; la mettre dans une fichier à part demanderais de la rendre paramétrable (En termes de taille / couleur), je sais pas si c'est le moment. Aucune objection @SylvainMarty ?

2018-10-08 13:42 UTC, BrunoGuerrero commented on src/index.js
>           *
Petite étoiles inutiles supprimées.
![image](https://user-images.githubusercontent.com/16825882/46612393-abf9f300-cb10-11e8-8d1e-2732e1e135cc.png)

2018-10-08 13:44 UTC, BrunoGuerrero commented on src/index.js
> +         *
![image](https://user-images.githubusercontent.com/16825882/46612500-01360480-cb11-11e8-9d9e-e1159b245fc1.png)

C'est corrigé.

2018-10-08 13:54 UTC, kmonmousseau approved these changes

2018-10-08 14:02 UTC, SylvainMarty approved these changes

2018-10-08 14:03 UTC, merged