Fix/reservation modal ios safari
Guidap/booking.js pull request #10
Opened 2019-03-08 11:13 UTC by ludolaloux13

Fixing the scrolling and display problem by creating an intermediate div, only on IOS Safari with an specific overflow and the atttribute "no scrolling" in the iframe.

2019-03-08 11:14 UTC, ludolaloux13 commented
Pour l'instant ça permet d'utiliser le module sur Safari IOS, mais le rendu n'est clairement pas aussi bien que sur Chrome ou Mozilla (les ancres ne fonctionnent pas et le bouton "reserver" ne reste pas en footer quand on scroll)

2019-03-11 15:30 UTC, ludolaloux13 commented
Comme vu avec Sylvain, on a toujours le même problème qui vient du zoom.

2019-04-09 08:24 UTC, SylvainMarty requested changes
2 remarques mais sinon on est good :+1:

2019-04-09 08:24 UTC, SylvainMarty commented on src/index.js
> +        let isSafaraIos = window.navigator.platform.includes('iPhone') && window.navigator.userAgent.includes('Safari')
```suggestion
        let isSafaraIos = window.navigator && window.navigator.platform && window.navigator.platform.includes('iPhone') && window.navigator.userAgent.includes('Safari');
```

2019-04-09 08:24 UTC, SylvainMarty commented on src/index.js
> +            } else _contentElement.setAttribute('style', 'position:absolute; left:5vw; top:5vh; width:90%; height:90vh; box-sizing: content-box; border:1px solid #E0E0E0; background-color:#fff; box-s
Manque les accolades ici :eyes: 
Et aussi, peux-tu mettre le style dupliqué dans une variable avant le if et simplement y ajouter tes spécificités pour safari IOS ? Ça évitera la duplication de code

2019-04-09 08:48 UTC, SylvainMarty approved these changes

2019-04-09 08:50 UTC, merged